server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sky_take_out?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456


sky:
  jwt:
    # 设置jwt签名加密时使用的秘钥
    admin-secret-key: 123qwe123123qwe123123qwe123123qwe123123qwe123123qwe123123qwe123123qwe123
    # 设置jwt过期时间
    admin-ttl: 7200000
    # 设置前端传递过来的令牌名称
    admin-token-name: token
    user-secret-key: 123qwe123123qwe123123qwe123123qwe123123qwe123123qwe123123qwe123123qwe123
    user-ttl: 7200000
    user-token-name: authentication
